### PR TITLE
add mac quick-setup

### PR DESCRIPTION
**Pull request by tringenbach**

### CODE REVIEW

**Comment by lersi** [comment]
Thank you very much for this amazing details! 
I like the fact that you mentions several ways to connect to the serial port, so users can choose what is best for them.

**Comment by tringenbach** [comment]
> Thank you very much for this amazing details! I like the fact that you mentions several ways to connect to the serial port, so users can choose what is best for them.

For what it's worth, what I've actually been using is `cu` with iTerm2 (version 3.4.22).

I'm using iTerm2 because, well, that's just the terminal I normally use for everything.

I tried using `screen` before I tried `cu`, and it worked but the colors were mostly missing. It that's something I could fix in either screen's configuration or in BusPirate's firmware, but I haven't dug into it since `cu` has been working for me. (At a previous job I used screen every day, but I changed jobs and haven't used it regularly in quite a while now.)

It took me a bit of googling to find something that worked to connect to BP, so I figured I should document it.


A lot of examples I found passed in baud and stop bit arguments, etc, but I found that those weren't necessary so I left them off to simplify the commands.

Also, I want to say I had to change a backspace / ^H setting in iTerm2, so that might be worth documenting too, but I wanted to get this out here sooner rather than later.

**Comment by lersi** [comment]
>  I could fix in either screen's configuration or in BusPirate's firmware. 


I have already added support for 256 ANSI colors in bus pirate firmware, it's the third option in the color configuration menu.
In addition, the release versions of `screen` do not yet support RGB colors, but the master branch is, so probably the next release of screen will support RGB colors

**Comment by tringenbach** [comment]
Ah, so that's what's going on!

Ok, I updated the PR to correctly explain the color situation. I also switched to consistently using the `cu.usbmodem` version of the devices, and a couple of other minor things.

Anything else I should change?

**Comment by DangerousPrototypes** [comment]
Thank you so much!

**Pull request merged**
